### ISSUE TITLE
Error with Workflow-Pages

### ISSUE THREAD

**Issue by DirkPersky** [clickstorm/cs_seo#177] opened 2018-06-22 07:21 UTC
- TYPO3: 8.7.16
- CS_SEO: 2.3.3
- Workflow: 8.7.16

Hi, when i created a new page within the workflow, changed the title from Page Tree and than modify the Page i even get This error.

Wehen i open the SEO-Module this happens too.
What can i do to fix this?

If you need TeamViewer access call me "+49-2563-929142"

**my constants:**
```
plugin.tx_csseo {
    # Page Pref Title
    sitetitle = XX - XX & XX - XX, XX, XX, XX
    # Sitemap.xml
    sitemap {
        pages {
            rootPid = 1
            languageUids = 0,1
        }
        extensions.news {
            storagePid = 18
            detailPid = 19
            languageUids = 0
        }
    }
    # Analytics
    tracking.googleAnalytics = XXXXX
    # hreflang config
    hreflang {
        enable = 1
        ids = 0,0,1
        keys = x-default,de,nl
    }
    # Default Social Image
    social.defaultImage = /fileadmin/user_upload/garten.jpg
}
```

**Error**
```
Uncaught TYPO3 Exception
Call to a member function stdWrap() on string 

Error thrown in file
/XXX_WEB_DIR/htdocs/typo3conf/ext/cs_seo/Classes/Utility/TSFEUtility.php in line 144.

24 Clickstorm\CsSeo\Utility\TSFEUtility::getPageTitleSeparator()

/XXX_WEB_DIR/htdocs/typo3conf/ext/cs_seo/Classes/UserFunc/PreviewWizard.php:
00198:                 if (isset($GLOBALS['TSFE'])) {
00199:                     $siteTitle = $TSFEUtility->getSiteTitle();
00200:                     $pageTitleSeparator = $TSFEUtility->getPageTitleSeparator();
00201:                     $config = $TSFEUtility->getConfig();
00202: 

23 Clickstorm\CsSeo\UserFunc\PreviewWizard::getBodyContent(array, "pages")

/XXX_WEB_DIR/htdocs/typo3conf/ext/cs_seo/Classes/UserFunc/PreviewWizard.php:
00100: 
00101:         // get Content
00102:         $content = $this->getBodyContent($cont['row'], $cont['table']);
00103: 
00104:         return $content;

22 Clickstorm\CsSeo\UserFunc\PreviewWizard::render(array, TYPO3\CMS\Backend\Form\Element\InputTextElement)
21 call_user_func_array(array, array)

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/core/Classes/Utility/GeneralUtility.php:
03835:                     }
03836:                     // Call method:
03837:                     $content = call_user_func_array([&$classObj, $parts[1]], [&$params, &$ref]);
03838:                 } else {
03839:                     $errorMsg = 'No method name \'' . $parts[1] . '\' in class ' . $parts[0];

20 TYPO3\CMS\Core\Utility\GeneralUtility::callUserFunction("Clickstorm\CsSeo\UserFunc\PreviewWizard->render", array, TYPO3\CMS\Backend\Form\Element\InputTextElement)

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/backend/Classes/Form/Element/AbstractFormElement.php:
00482:                     $params['wConf'] = $wizardConfiguration;
00483:                     $params['row'] = $row;
00484:                     $otherWizards[] = GeneralUtility::callUserFunction($wizardConfiguration['userFunc'], $params, $this);
00485:                     break;
00486: 

19 TYPO3\CMS\Backend\Form\Element\AbstractFormElement::renderWizards()

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/backend/Classes/Form/Element/InputTextElement.php:
00200:         }
00201: 
00202:         $legacyWizards = $this->renderWizards();
00203:         $legacyFieldControlHtml = implode(LF, $legacyWizards['fieldControl']);
00204:         $legacyFieldWizardHtml = implode(LF, $legacyWizards['fieldWizard']);

18 TYPO3\CMS\Backend\Form\Element\InputTextElement::render()

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/backend/Classes/Form/Container/SingleFieldContainer.php:
00179:             $options['renderType'] = $parameterArray['fieldConf']['config']['type'];
00180:         }
00181:         $resultArray = $this->nodeFactory->create($options)->render();
00182:         return $resultArray;
00183:     }

17 TYPO3\CMS\Backend\Form\Container\SingleFieldContainer::render()

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/backend/Classes/Form/Container/PaletteAndSingleContainer.php:
00212: 
00213:                 $options['renderType'] = 'singleFieldContainer';
00214:                 $singleFieldContentArray = $this->nodeFactory->create($options)->render();
00215: 
00216:                 if (!empty($singleFieldContentArray['html'])) {

16 TYPO3\CMS\Backend\Form\Container\PaletteAndSingleContainer::createPaletteContentArray("tx_csseo_preview")

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/backend/Classes/Form/Container/PaletteAndSingleContainer.php:
00115:             $fieldName = $fieldConfiguration['fieldName'];
00116:             if ($fieldName === '--palette--') {
00117:                 $paletteElementArray = $this->createPaletteContentArray($fieldConfiguration['paletteName']);
00118:                 if (!empty($paletteElementArray)) {
00119:                     $mainStructureCounter ++;

15 TYPO3\CMS\Backend\Form\Container\PaletteAndSingleContainer::render()

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/backend/Classes/Form/Container/TabsContainer.php:
00084:             }
00085:             $options['renderType'] = 'paletteAndSingleContainer';
00086:             $childArray = $this->nodeFactory->create($options)->render();
00087: 
00088:             $tabElements[] = [

14 TYPO3\CMS\Backend\Form\Container\TabsContainer::render()

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/backend/Classes/Form/Container/FullRecordContainer.php:
00081:         }
00082: 
00083:         return $this->nodeFactory->create($data)->render();
00084:     }
00085: 

13 TYPO3\CMS\Backend\Form\Container\FullRecordContainer::render()

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/backend/Classes/Form/Container/OuterWrapContainer.php:
00052:             $options['renderType'] = 'listOfFieldsContainer';
00053:         }
00054:         $result = $this->nodeFactory->create($options)->render();
00055: 
00056:         $childHtml = $result['html'];

12 TYPO3\CMS\Backend\Form\Container\OuterWrapContainer::render()

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/backend/Classes/Controller/EditDocumentController.php:
01106: 
01107:                                 $formData['renderType'] = 'outerWrapContainer';
01108:                                 $formResult = $nodeFactory->create($formData)->render();
01109: 
01110:                                 $html = $formResult['html'];

11 TYPO3\CMS\Backend\Controller\EditDocumentController::makeEditForm()

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/backend/Classes/Controller/EditDocumentController.php:
00929: 
00930:             // Creating the editing form, wrap it with buttons, document selector etc.
00931:             $editForm = $this->makeEditForm();
00932:             if ($editForm) {
00933:                 $this->firstEl = reset($this->elementsData);

10 TYPO3\CMS\Backend\Controller\EditDocumentController::main()

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/backend/Classes/Controller/EditDocumentController.php:
02111: 
02112:         $this->init();
02113:         $this->main();
02114: 
02115:         $response->getBody()->write($this->moduleTemplate->renderContent());

9 TYPO3\CMS\Backend\Controller\EditDocumentController::mainAction(TYPO3\CMS\Core\Http\ServerRequest, TYPO3\CMS\Core\Http\Response)
8 call_user_func_array(array, array)

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/backend/Classes/Http/RouteDispatcher.php:
00052:         $targetIdentifier = $route->getOption('target');
00053:         $target = $this->getCallableFromTarget($targetIdentifier);
00054:         return call_user_func_array($target, [$request, $response]);
00055:     }
00056: 

7 TYPO3\CMS\Backend\Http\RouteDispatcher::dispatch(TYPO3\CMS\Core\Http\ServerRequest, TYPO3\CMS\Core\Http\Response)

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/backend/Classes/Http/RequestHandler.php:
00137:         /** @var RouteDispatcher $dispatcher */
00138:         $dispatcher = GeneralUtility::makeInstance(RouteDispatcher::class);
00139:         return $dispatcher->dispatch($request, $response);
00140:     }
00141: }

6 TYPO3\CMS\Backend\Http\RequestHandler::dispatch(TYPO3\CMS\Core\Http\ServerRequest)

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/backend/Classes/Http/RequestHandler.php:
00070:         // Check if the router has the available route and dispatch.
00071:         try {
00072:             return $this->dispatch($request);
00073:         } catch (InvalidRequestTokenException $e) {
00074:             // When token was invalid redirect to login

5 TYPO3\CMS\Backend\Http\RequestHandler::handleRequest(TYPO3\CMS\Core\Http\ServerRequest)

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/core/Classes/Core/Bootstrap.php:
00313: 
00314:         // Execute the command which returns a Response object or NULL
00315:         $this->response = $requestHandler->handleRequest($request);
00316:         return $this;
00317:     }

4 TYPO3\CMS\Core\Core\Bootstrap::handleRequest(TYPO3\CMS\Core\Http\ServerRequest)

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/backend/Classes/Http/Application.php:
00090:         }
00091: 
00092:         $this->bootstrap->handleRequest($this->request);
00093: 
00094:         if ($execute !== null) {

3 TYPO3\CMS\Backend\Http\Application::run()

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/backend/Resources/Private/Php/backend.php:
00022:     $classLoader = require __DIR__ . '/../../../../../../vendor/autoload.php';
00023: 
00024:     (new \TYPO3\CMS\Backend\Http\Application($classLoader))->run();
00025: });

2 {closure}()

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/sysext/backend/Resources/Private/Php/backend.php:
00023: 
00024:     (new \TYPO3\CMS\Backend\Http\Application($classLoader))->run();
00025: });

1 require("/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.1…3/sysext/backend/Resources/Private/Php/backend.php")

/XXX_GLOBAL_TYP3_DIR/typo3_src-8.7.16/typo3/index.php:
00001: <?php
00002: 
00003: require __DIR__ . '/sysext/backend/Resources/Private/Php/backend.php';

```

**Comment by clickstorm** [comment] 2018-06-29 14:48
Hey thanks for the hint. We had this error in the past #40 . Maybe it is here another reason, while the TSFE can not be initialized. I would like to test this, but I can't reproduce the error. I will call you on monday. Have a nice weekend.

**Comment by DirkPersky** [comment] 2018-06-29 15:13
okay if you not reach me, try this number:   +49 2564 3980770

**Comment by clickstorm** [comment] 2018-07-03 09:46
Hey. The error occured when you add a new page and a page overlay in a workspace and then whant to edit the page settings of the overlay. This is fixed in the 2x branch. I will release a new bugfix version. Before maybe you like to test?

**Closed by clickstorm** 2018-07-03 09:46 UTC

**Comment by DirkPersky** [comment] 2018-07-04 11:08
Yes it works!

thx 4 helping
